### ISSUE TITLE
jhm-folder

### ISSUE THREAD

**Issue by jeonhyoungmin** [jeonhyoungmin/project-hackathon#11]
WDJ 팀원에게 요청

폴더 정리 완료

Error 발생

등록 Modal 창 버튼 로고 Error 해결 요청

**Comment by WonDuJin** [comment]
SocialSigninButon.js에서 import된 NaverSign url 
위치 마지막에 .js붙이니까 해결

**Comment by WonDuJin** [comment]
북마크 페이지 + 버튼 미출력 현상 수정  : addbox 경로문제였음
keyword undefinded 오류 수정 : export 선언시 명칭선언 오류
