### ISSUE TITLE
wdj-third-cycle

### ISSUE THREAD

**Issue by jeonhyoungmin** [jeonhyoungmin/project-hackathon#4]
Third-party 로그인(소셜 로그인)으로

앱 한 사이클 돌려보기

과정: 소셜 로그인 => 북마크 등록 => DB 저장 확인 => 로그아웃 후 확인 => 소셜 로그인 후 확인

필요 조건: DB diagram 테이블 연결 - index INT를 PK로 설정

※ table instance 필요 유무 확인

**Comment by WonDuJin** [comment]
확인완료
