### ISSUE TITLE
wdj-mainpage

### ISSUE THREAD

**Issue by jeonhyoungmin** [jeonhyoungmin/project-hackathon#7]
mainpage 추가 제작 요청

1. 추가 버튼 위치 변경

2. 데이터 등록 박스 제작

**Comment by jeonhyoungmin** [comment]
mainpage 제작하기 위한 브랜치였지만,

소셜 로그인 db 저장 문제 발생으로 내용 변경

변경 내용: 소셜 로그인 DB 저장 문제 해결

**Comment by WonDuJin** [comment]
해결완료
