### ISSUE TITLE
wdj-naver-db

### ISSUE THREAD

**Issue by jeonhyoungmin** [jeonhyoungmin/project-hackathon#9]
Naver 소셜 로그인(서드 파티)

데이터 DB 저장 기능 구현 요청

이후에 메인페이지 제작

**Comment by jeonhyoungmin** [comment]
일반 로그인과 소셜 로그인 merge 문제 해결

일반 로그인: session 기능 사용

소셜 로그인: AsyncStorage 기능 사용

session, AsyncStorage 두 가지 기능 모두 사용해보기 위해 혼용

**Comment by WonDuJin** [comment]
수정완료
